[package]
name = "lexicon-ty"
version = "0.0.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true